server:
  port: 8080

spring:
  application:
    name: discodeit
  boot:
    admin:
      client:
        url: http://localhost:9090
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit_dev
    username: dev_user
    password: dev1234

logging:
  level:
    root: info
    com.sprint: info