server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://discodeit-db.cri22gkiskwr.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: discodeit_user
    password: discodeit1234
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true