server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit_dev
    username: dev_user
    password: dev1234

logging:
  level:
    root: debug
    com.sprint: debug